
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/dev

test:
  <<: *default
  database: db/tes

production:
  <<: *default
  database: db/productin
